compatibility_date = "2021-11-01"
compatibility_flags = []
name = "vavite-testbed"
route = ''
site = {entry-point = "dist/cfw-bundle.js"}
type = "javascript"
usage_model = ''
workers_dev = true
zone_id = ''

[build]
command = "DEPLOY_TARGET=cfw npm run build"

[build.upload]
format = "module"
